Fix gcc gperf prototypes to avoid redeclaration errors
Otherwise, building stable/12's gcc on recent -CURRENT will result in
redeclaration errors:

In file included from /usr/src/contrib/gcc/cp/except.c:892:
/usr/src/contrib/gcc/cp/cfns.gperf:20:1: error: conflicting types for 'hash'
hash (register const char *str, register size_t len)
^
/usr/src/contrib/gcc/cp/cfns.gperf:5:21: note: previous declaration is here
static unsigned int hash (const char *, unsigned int);
                    ^
/usr/src/contrib/gcc/cp/cfns.gperf:78:1: error: conflicting types for 'libc_name_p'
libc_name_p (register const char *str, register size_t len)
^
/usr/src/contrib/gcc/cp/cfns.gperf:9:14: note: previous declaration is here
const char * libc_name_p (const char *, unsigned int);
             ^

Direct commit to stable/12, since gcc is gone in stable/13 and later.